
package com.zhangying.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherInterface", targetNamespace = "http://webservice.zhangying.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.zhangying.webservice.WeatherModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://webservice.zhangying.com", className = "com.zhangying.webservice.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://webservice.zhangying.com", className = "com.zhangying.webservice.QueryWeatherResponse")
    public List<WeatherModel> queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
